#pragma config(Sensor, S1,     accel,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Collision.h"


task main()
{

	StartTask(Collision);
	motor[motorB] = 100;

	motor[motorC] = 100;

	while(true)

	{



		if(movement == 1)

		{

		nxtDisplayBigTextLine(3, "move");


		}

		else if(movement == 2)

		{


			//PlaySound(soundException);
			motor[motorB] = 0;

			motor[motorC] = 0;


		}

	}

}
