#pragma config(Sensor, S1,     accel,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Collision.h"


task main()
{

	StartTask(Collision);

	while(true)

	{

		wait1Msec(2000);

		motor[motorB] = 100;

		motor[motorC] = 100;



		while(true)

		{



			if(movement == 1)

			{

				//PlaySound(soundBeepBeep);

				//nxtDisplayBigTextLine(3, "move");


			}

			else if(movement == 2)

			{


				//PlaySound(soundException);
				motor[motorB] = 0;

				motor[motorC] = 0;


			}

		}

	}
}
